### PR TITLE
Spacing bug

### PR DESCRIPTION
**Pull request by nvs-abhilash**
The bug was while joining in the auth function.

### CODE REVIEW

**Comment by nvs-abhilash** [comment]
@piyush-jaiswal This branch was updated on top of #22. So, I suggest you review #22  first, then this one.

**Comment by piyush-jaiswal** [comment]
Great work. Let's keep it up.

**Comment by piyush-jaiswal** [comment]
A single space is introduced before the first word when correcting the first word. We could fix it in this PR itself or open up a separate issue since I have already merged this PR. Your call.

**Comment by nvs-abhilash** [comment]
Let's open up a new one to fix the UI, cause there are a lot more problems that I discovered while solving this simple bug: 
* After clicking the buttons we need to put the cursor back to the text, which does not happen yet. 
* Also fixing the variable naming (`user` and `auth` needs to be replaced). 
* Moving design stuff to a `.kv` file and logic stuff is `.py`. Currently all is in `.py` file.

Let's open up a new issue covering all of this. And that starting space could be added with this ;) 

P.S.: Nice observation on finding the initial space. This makes me wonder, we should have some form of testing or C.I. system to catch these and other kinds of error in future.

**Pull request merged**
